// Generated by scripts/extract-game-data.mjs. Do not edit by hand.

export type ChessCost = 1 | 2 | 3 | 4 | 5;

export interface PieceData {
  id: string;
  name: string;
  cost: ChessCost;
  order: number;
  sourceOrder: number;
  synergies: string[];
  icon: string | null;
  initialCopies: number;
  copies: number;
}

export interface SynergyData {
  id: string;
  name: string;
  kind: "race" | "class";
  pieceIds: string[];
}

export interface GameData {
  pieces: PieceData[];
  synergies: SynergyData[];
  io: { id: "chess_io"; name: string; cost: 5; icon: string | null };
}

export const gameData: GameData = {
  "pieces": [
    {
      "id": "chess_bane",
      "cost": 1,
      "order": 0,
      "sourceOrder": 0,
      "name": "祸乱之源",
      "synergies": [
        "is_satyr",
        "is_nraqi",
        "is_warlock"
      ],
      "icon": null,
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_tusk",
      "cost": 1,
      "order": 1,
      "sourceOrder": 1,
      "name": "巨牙海民",
      "synergies": [
        "is_beast",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_tusk.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_dw",
      "cost": 1,
      "order": 2,
      "sourceOrder": 2,
      "name": "邪影芳灵",
      "synergies": [
        "is_elf",
        "is_wizard"
      ],
      "icon": "/chess-icons/chess_dw.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_pom",
      "cost": 1,
      "order": 3,
      "sourceOrder": 3,
      "name": "月之女祭司",
      "synergies": [
        "is_elf",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_pom.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_dazzle",
      "cost": 1,
      "order": 4,
      "sourceOrder": 4,
      "name": "暗影牧师",
      "synergies": [
        "is_troll",
        "is_priest"
      ],
      "icon": "/chess-icons/chess_dazzle.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_cm",
      "cost": 1,
      "order": 5,
      "sourceOrder": 5,
      "name": "水晶室女",
      "synergies": [
        "is_human",
        "is_mage"
      ],
      "icon": "/chess-icons/chess_cm.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_aa",
      "cost": 1,
      "order": 6,
      "sourceOrder": 6,
      "name": "极寒幽魂",
      "synergies": [
        "is_element",
        "is_mage"
      ],
      "icon": null,
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_axe",
      "cost": 1,
      "order": 7,
      "sourceOrder": 7,
      "name": "斧王",
      "synergies": [
        "is_orc",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_axe.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_eh",
      "cost": 1,
      "order": 8,
      "sourceOrder": 8,
      "name": "魅惑魔女",
      "synergies": [
        "is_beast",
        "is_centaur",
        "is_druid"
      ],
      "icon": "/chess-icons/chess_eh.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_clock",
      "cost": 1,
      "order": 9,
      "sourceOrder": 9,
      "name": "发条技师",
      "synergies": [
        "is_goblin",
        "is_mech"
      ],
      "icon": "/chess-icons/chess_clock.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_ss",
      "cost": 1,
      "order": 10,
      "sourceOrder": 10,
      "name": "暗影萨满",
      "synergies": [
        "is_troll",
        "is_shaman"
      ],
      "icon": "/chess-icons/chess_ss.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_tk",
      "cost": 1,
      "order": 11,
      "sourceOrder": 11,
      "name": "修补匠",
      "synergies": [
        "is_goblin",
        "is_mech"
      ],
      "icon": "/chess-icons/chess_tk.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_mars",
      "cost": 1,
      "order": 12,
      "sourceOrder": 12,
      "name": "天界战神",
      "synergies": [
        "is_god",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_mars.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_wd",
      "cost": 1,
      "order": 13,
      "sourceOrder": 13,
      "name": "巫医",
      "synergies": [
        "is_troll",
        "is_warlock"
      ],
      "icon": "/chess-icons/chess_wd.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_sb",
      "cost": 1,
      "order": 14,
      "sourceOrder": 14,
      "name": "裂魂人",
      "synergies": [
        "is_tauren",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_sb.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_hw",
      "cost": 1,
      "order": 15,
      "sourceOrder": 15,
      "name": "森海飞霞",
      "synergies": [
        "is_beast",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_hw.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_bh",
      "cost": 1,
      "order": 16,
      "sourceOrder": 16,
      "name": "赏金猎人",
      "synergies": [
        "is_draenei",
        "is_goblin",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_bh.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_sd",
      "cost": 1,
      "order": 17,
      "sourceOrder": 17,
      "name": "暗影恶魔",
      "synergies": [
        "is_draenei",
        "is_demon",
        "is_priest"
      ],
      "icon": null,
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_sm",
      "cost": 1,
      "order": 18,
      "sourceOrder": 18,
      "name": "天怒法师",
      "synergies": [
        "is_harpy",
        "is_mage"
      ],
      "icon": null,
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_brew",
      "cost": 1,
      "order": 19,
      "sourceOrder": 19,
      "name": "熊猫酒仙",
      "synergies": [
        "is_pandaman",
        "is_monk"
      ],
      "icon": "/chess-icons/chess_brew.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_luna",
      "cost": 2,
      "order": 20,
      "sourceOrder": 20,
      "name": "月之骑士",
      "synergies": [
        "is_elf",
        "is_knight"
      ],
      "icon": "/chess-icons/chess_luna.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_lina",
      "cost": 2,
      "order": 21,
      "sourceOrder": 21,
      "name": "秀逗魔导士",
      "synergies": [
        "is_human",
        "is_mage"
      ],
      "icon": "/chess-icons/chess_lina.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_bs",
      "cost": 2,
      "order": 22,
      "sourceOrder": 22,
      "name": "血魔",
      "synergies": [
        "is_orc",
        "is_shaman"
      ],
      "icon": "/chess-icons/chess_bs.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_wr",
      "cost": 2,
      "order": 23,
      "sourceOrder": 23,
      "name": "风行者",
      "synergies": [
        "is_elf",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_wr.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_fv",
      "cost": 2,
      "order": 24,
      "sourceOrder": 24,
      "name": "虚空假面",
      "synergies": [
        "is_nraqi",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_fv.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_bm",
      "cost": 2,
      "order": 25,
      "sourceOrder": 25,
      "name": "兽王",
      "synergies": [
        "is_orc",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_bm.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_jugg",
      "cost": 2,
      "order": 26,
      "sourceOrder": 26,
      "name": "剑圣",
      "synergies": [
        "is_orc",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_jugg.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_shredder",
      "cost": 2,
      "order": 27,
      "sourceOrder": 27,
      "name": "伐木机",
      "synergies": [
        "is_goblin",
        "is_mech"
      ],
      "icon": "/chess-icons/chess_shredder.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_slark",
      "cost": 2,
      "order": 28,
      "sourceOrder": 28,
      "name": "鱼人夜行者",
      "synergies": [
        "is_naga",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_slark.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_ck",
      "cost": 2,
      "order": 29,
      "sourceOrder": 29,
      "name": "混沌骑士",
      "synergies": [
        "is_demon",
        "is_knight"
      ],
      "icon": "/chess-icons/chess_ck.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_fur",
      "cost": 2,
      "order": 30,
      "sourceOrder": 30,
      "name": "先知",
      "synergies": [
        "is_elf",
        "is_druid"
      ],
      "icon": "/chess-icons/chess_fur.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_bat",
      "cost": 2,
      "order": 31,
      "sourceOrder": 31,
      "name": "蝙蝠骑士",
      "synergies": [
        "is_troll",
        "is_knight"
      ],
      "icon": "/chess-icons/chess_bat.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_meepo",
      "cost": 2,
      "order": 32,
      "sourceOrder": 32,
      "name": "地卜师",
      "synergies": [
        "is_kobold",
        "is_mech"
      ],
      "icon": "/chess-icons/chess_meepo.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_sniper",
      "cost": 2,
      "order": 33,
      "sourceOrder": 33,
      "name": "狙击手",
      "synergies": [
        "is_dwarf",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_sniper.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_largo",
      "cost": 2,
      "order": 34,
      "sourceOrder": 34,
      "name": "云游乐手",
      "synergies": [
        "is_naga",
        "is_monk"
      ],
      "icon": null,
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_puck",
      "cost": 2,
      "order": 35,
      "sourceOrder": 35,
      "name": "仙女龙",
      "synergies": [
        "is_elf",
        "is_dragon",
        "is_mage"
      ],
      "icon": "/chess-icons/chess_puck.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_tiny",
      "cost": 2,
      "order": 36,
      "sourceOrder": 36,
      "name": "山岭巨人",
      "synergies": [
        "is_element",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_tiny.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_oracle",
      "cost": 2,
      "order": 37,
      "sourceOrder": 37,
      "name": "神谕者",
      "synergies": [
        "is_god",
        "is_priest"
      ],
      "icon": "/chess-icons/chess_oracle.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_ct",
      "cost": 2,
      "order": 38,
      "sourceOrder": 38,
      "name": "半人马战行者",
      "synergies": [
        "is_centaur",
        "is_warrior"
      ],
      "icon": null,
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_ds",
      "cost": 2,
      "order": 39,
      "sourceOrder": 39,
      "name": "黑暗贤者",
      "synergies": [
        "is_draenei",
        "is_warlock"
      ],
      "icon": null,
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_gs",
      "cost": 2,
      "order": 40,
      "sourceOrder": 40,
      "name": "天涯墨客",
      "synergies": [
        "is_demon",
        "is_wizard"
      ],
      "icon": "/chess-icons/chess_gs.png",
      "initialCopies": 20,
      "copies": 20
    },
    {
      "id": "chess_lyc",
      "cost": 3,
      "order": 41,
      "sourceOrder": 41,
      "name": "狼人",
      "synergies": [
        "is_human",
        "is_beast",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_lyc.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_slardar",
      "cost": 3,
      "order": 42,
      "sourceOrder": 42,
      "name": "鱼人守卫",
      "synergies": [
        "is_naga",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_slardar.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_viper",
      "cost": 3,
      "order": 43,
      "sourceOrder": 43,
      "name": "冥界亚龙",
      "synergies": [
        "is_dragon",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_viper.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_razor",
      "cost": 3,
      "order": 44,
      "sourceOrder": 44,
      "name": "闪电幽魂",
      "synergies": [
        "is_element",
        "is_shaman"
      ],
      "icon": "/chess-icons/chess_razor.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_enigma",
      "cost": 3,
      "order": 45,
      "sourceOrder": 45,
      "name": "谜团",
      "synergies": [
        "is_element",
        "is_warlock"
      ],
      "icon": "/chess-icons/chess_enigma.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_tp",
      "cost": 3,
      "order": 46,
      "sourceOrder": 46,
      "name": "树精卫士",
      "synergies": [
        "is_elf",
        "is_druid"
      ],
      "icon": "/chess-icons/chess_tp.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_es",
      "cost": 3,
      "order": 47,
      "sourceOrder": 47,
      "name": "撼地神牛",
      "synergies": [
        "is_tauren",
        "is_shaman"
      ],
      "icon": "/chess-icons/chess_es.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_veno",
      "cost": 3,
      "order": 48,
      "sourceOrder": 48,
      "name": "剧毒术士",
      "synergies": [
        "is_beast",
        "is_aqir",
        "is_warlock"
      ],
      "icon": "/chess-icons/chess_veno.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_sk",
      "cost": 3,
      "order": 49,
      "sourceOrder": 49,
      "name": "沙王",
      "synergies": [
        "is_aqir",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_sk.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_naga",
      "cost": 3,
      "order": 50,
      "sourceOrder": 50,
      "name": "娜迦海妖",
      "synergies": [
        "is_naga",
        "is_wizard"
      ],
      "icon": "/chess-icons/chess_naga.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_rubick",
      "cost": 3,
      "order": 51,
      "sourceOrder": 51,
      "name": "大魔导师",
      "synergies": [
        "is_god",
        "is_wizard"
      ],
      "icon": "/chess-icons/chess_rubick.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_lc",
      "cost": 3,
      "order": 52,
      "sourceOrder": 52,
      "name": "军团指挥官",
      "synergies": [
        "is_human",
        "is_knight"
      ],
      "icon": "/chess-icons/chess_lc.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_huskar",
      "cost": 3,
      "order": 53,
      "sourceOrder": 53,
      "name": "神灵武士",
      "synergies": [
        "is_troll",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_huskar.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_marci",
      "cost": 3,
      "order": 54,
      "sourceOrder": 54,
      "name": "月之哨卫",
      "synergies": [
        "is_elf",
        "is_monk"
      ],
      "icon": "/chess-icons/chess_marci.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_riki",
      "cost": 3,
      "order": 55,
      "sourceOrder": 55,
      "name": "隐形刺客",
      "synergies": [
        "is_satyr",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_riki.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_sf",
      "cost": 3,
      "order": 56,
      "sourceOrder": 56,
      "name": "影魔",
      "synergies": [
        "is_demon",
        "is_warlock"
      ],
      "icon": "/chess-icons/chess_sf.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_tb",
      "cost": 3,
      "order": 57,
      "sourceOrder": 57,
      "name": "灵魂守卫",
      "synergies": [
        "is_demon",
        "is_demonhunter"
      ],
      "icon": "/chess-icons/chess_tb.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_db",
      "cost": 3,
      "order": 58,
      "sourceOrder": 58,
      "name": "破晓辰星",
      "synergies": [
        "is_draenei",
        "is_knight"
      ],
      "icon": null,
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_om",
      "cost": 3,
      "order": 59,
      "sourceOrder": 59,
      "name": "食人魔魔法师",
      "synergies": [
        "is_ogre",
        "is_mage"
      ],
      "icon": "/chess-icons/chess_om.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_kez",
      "cost": 3,
      "order": 60,
      "sourceOrder": 60,
      "name": "影武者",
      "synergies": [
        "is_harpy",
        "is_assassin"
      ],
      "icon": null,
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_am",
      "cost": 4,
      "order": 61,
      "sourceOrder": 61,
      "name": "敌法师",
      "synergies": [
        "is_elf",
        "is_demonhunter"
      ],
      "icon": "/chess-icons/chess_am.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_pa",
      "cost": 4,
      "order": 62,
      "sourceOrder": 62,
      "name": "幻影刺客",
      "synergies": [
        "is_elf",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_pa.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_dk",
      "cost": 4,
      "order": 63,
      "sourceOrder": 63,
      "name": "龙骑士",
      "synergies": [
        "is_human",
        "is_dragon",
        "is_knight"
      ],
      "icon": "/chess-icons/chess_dk.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_phx",
      "cost": 4,
      "order": 64,
      "sourceOrder": 64,
      "name": "凤凰",
      "synergies": [
        "is_element",
        "is_mage"
      ],
      "icon": null,
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_doom",
      "cost": 4,
      "order": 65,
      "sourceOrder": 65,
      "name": "末日使者",
      "synergies": [
        "is_demon",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_doom.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_medusa",
      "cost": 4,
      "order": 66,
      "sourceOrder": 66,
      "name": "蛇发女妖",
      "synergies": [
        "is_naga",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_medusa.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_et",
      "cost": 4,
      "order": 67,
      "sourceOrder": 67,
      "name": "上古巨神",
      "synergies": [
        "is_god",
        "is_tauren",
        "is_druid"
      ],
      "icon": "/chess-icons/chess_et.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_ga",
      "cost": 4,
      "order": 68,
      "sourceOrder": 68,
      "name": "炼金术士",
      "synergies": [
        "is_goblin",
        "is_ogre",
        "is_warlock"
      ],
      "icon": "/chess-icons/chess_ga.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_light",
      "cost": 4,
      "order": 69,
      "sourceOrder": 69,
      "name": "光之守卫",
      "synergies": [
        "is_human",
        "is_mage"
      ],
      "icon": "/chess-icons/chess_light.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_ld",
      "cost": 4,
      "order": 70,
      "sourceOrder": 70,
      "name": "利爪德鲁伊",
      "synergies": [
        "is_beast",
        "is_druid"
      ],
      "icon": "/chess-icons/chess_ld.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_pangolier",
      "cost": 4,
      "order": 71,
      "sourceOrder": 71,
      "name": "石鳞剑士",
      "synergies": [
        "is_beast",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_pangolier.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_chen",
      "cost": 4,
      "order": 72,
      "sourceOrder": 72,
      "name": "上帝之手",
      "synergies": [
        "is_orc",
        "is_priest"
      ],
      "icon": "/chess-icons/chess_chen.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_kunkka",
      "cost": 4,
      "order": 73,
      "sourceOrder": 73,
      "name": "海军上将",
      "synergies": [
        "is_human",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_kunkka.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_snap",
      "cost": 4,
      "order": 74,
      "sourceOrder": 74,
      "name": "电炎绝手",
      "synergies": [
        "is_goblin",
        "is_knight"
      ],
      "icon": "/chess-icons/chess_snap.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_mk",
      "cost": 4,
      "order": 75,
      "sourceOrder": 75,
      "name": "齐天大圣",
      "synergies": [
        "is_beast",
        "is_monk"
      ],
      "icon": "/chess-icons/chess_mk.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_mag",
      "cost": 4,
      "order": 76,
      "sourceOrder": 76,
      "name": "半人猛犸",
      "synergies": [
        "is_centaur",
        "is_assassin"
      ],
      "icon": null,
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_br",
      "cost": 4,
      "order": 77,
      "sourceOrder": 77,
      "name": "育母蜘蛛",
      "synergies": [
        "is_aqir",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_br.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_lion",
      "cost": 4,
      "order": 78,
      "sourceOrder": 78,
      "name": "恶魔巫师",
      "synergies": [
        "is_demon",
        "is_wizard"
      ],
      "icon": "/chess-icons/chess_lion.png",
      "initialCopies": 15,
      "copies": 15
    },
    {
      "id": "chess_ok",
      "cost": 5,
      "order": 79,
      "sourceOrder": 79,
      "name": "全能骑士",
      "synergies": [
        "is_human",
        "is_knight"
      ],
      "icon": "/chess-icons/chess_ok.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_ta",
      "cost": 5,
      "order": 80,
      "sourceOrder": 80,
      "name": "圣堂刺客",
      "synergies": [
        "is_elf",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_ta.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_morph",
      "cost": 5,
      "order": 81,
      "sourceOrder": 81,
      "name": "变体精灵",
      "synergies": [
        "is_element",
        "is_elf",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_morph.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_gyro",
      "cost": 5,
      "order": 82,
      "sourceOrder": 82,
      "name": "矮人直升机",
      "synergies": [
        "is_mech",
        "is_dwarf"
      ],
      "icon": "/chess-icons/chess_gyro.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_thd",
      "cost": 5,
      "order": 83,
      "sourceOrder": 83,
      "name": "双头龙",
      "synergies": [
        "is_dragon",
        "is_mage"
      ],
      "icon": "/chess-icons/chess_thd.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_tech",
      "cost": 5,
      "order": 84,
      "sourceOrder": 84,
      "name": "地精工程师",
      "synergies": [
        "is_goblin",
        "is_mech"
      ],
      "icon": "/chess-icons/chess_tech.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_zeus",
      "cost": 5,
      "order": 85,
      "sourceOrder": 85,
      "name": "众神之王",
      "synergies": [
        "is_god",
        "is_mage"
      ],
      "icon": "/chess-icons/chess_zeus.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_ts",
      "cost": 5,
      "order": 86,
      "sourceOrder": 86,
      "name": "受折磨的灵魂",
      "synergies": [
        "is_god",
        "is_centaur",
        "is_druid"
      ],
      "icon": null,
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_qop",
      "cost": 5,
      "order": 87,
      "sourceOrder": 87,
      "name": "痛苦女王",
      "synergies": [
        "is_demon",
        "is_assassin"
      ],
      "icon": "/chess-icons/chess_qop.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_wl",
      "cost": 5,
      "order": 88,
      "sourceOrder": 88,
      "name": "术士",
      "synergies": [
        "is_orc",
        "is_warlock"
      ],
      "icon": "/chess-icons/chess_wl.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_troll",
      "cost": 5,
      "order": 89,
      "sourceOrder": 89,
      "name": "巨魔战将",
      "synergies": [
        "is_troll",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_troll.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_aw",
      "cost": 5,
      "order": 90,
      "sourceOrder": 90,
      "name": "天穹守望者",
      "synergies": [
        "is_kobold",
        "is_shaman"
      ],
      "icon": "/chess-icons/chess_aw.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_disruptor",
      "cost": 5,
      "order": 91,
      "sourceOrder": 91,
      "name": "干扰者",
      "synergies": [
        "is_orc",
        "is_shaman"
      ],
      "icon": "/chess-icons/chess_disruptor.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_th",
      "cost": 5,
      "order": 92,
      "sourceOrder": 92,
      "name": "潮汐猎人",
      "synergies": [
        "is_naga",
        "is_hunter"
      ],
      "icon": "/chess-icons/chess_th.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_pb",
      "cost": 5,
      "order": 93,
      "sourceOrder": 93,
      "name": "原始巨兽",
      "synergies": [
        "is_beast",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_pb.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_kael",
      "cost": 5,
      "order": 94,
      "sourceOrder": 94,
      "name": "祈求者",
      "synergies": [
        "is_elf",
        "is_mage"
      ],
      "icon": "/chess-icons/chess_kael.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_sven",
      "cost": 5,
      "order": 95,
      "sourceOrder": 95,
      "name": "流浪剑客",
      "synergies": [
        "is_demon",
        "is_warrior"
      ],
      "icon": "/chess-icons/chess_sven.png",
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_rm",
      "cost": 5,
      "order": 96,
      "sourceOrder": 96,
      "name": "百戏大王",
      "synergies": [],
      "icon": null,
      "initialCopies": 10,
      "copies": 10
    },
    {
      "id": "chess_au",
      "cost": 5,
      "order": 97,
      "sourceOrder": 97,
      "name": "孽主",
      "synergies": [
        "is_demon",
        "is_warlock"
      ],
      "icon": null,
      "initialCopies": 10,
      "copies": 10
    }
  ],
  "synergies": [
    {
      "id": "is_aqir",
      "name": "虫",
      "kind": "race",
      "pieceIds": [
        "chess_veno",
        "chess_sk",
        "chess_br"
      ]
    },
    {
      "id": "is_beast",
      "name": "野兽",
      "kind": "race",
      "pieceIds": [
        "chess_tusk",
        "chess_eh",
        "chess_hw",
        "chess_lyc",
        "chess_veno",
        "chess_ld",
        "chess_pangolier",
        "chess_mk",
        "chess_pb"
      ]
    },
    {
      "id": "is_demon",
      "name": "恶魔",
      "kind": "race",
      "pieceIds": [
        "chess_sd",
        "chess_ck",
        "chess_gs",
        "chess_sf",
        "chess_tb",
        "chess_doom",
        "chess_lion",
        "chess_qop",
        "chess_sven",
        "chess_au"
      ]
    },
    {
      "id": "is_dragon",
      "name": "龙",
      "kind": "race",
      "pieceIds": [
        "chess_puck",
        "chess_viper",
        "chess_dk",
        "chess_thd"
      ]
    },
    {
      "id": "is_dwarf",
      "name": "矮人",
      "kind": "race",
      "pieceIds": [
        "chess_sniper",
        "chess_gyro"
      ]
    },
    {
      "id": "is_element",
      "name": "元素",
      "kind": "race",
      "pieceIds": [
        "chess_aa",
        "chess_tiny",
        "chess_razor",
        "chess_enigma",
        "chess_phx",
        "chess_morph"
      ]
    },
    {
      "id": "is_elf",
      "name": "精灵",
      "kind": "race",
      "pieceIds": [
        "chess_dw",
        "chess_pom",
        "chess_luna",
        "chess_wr",
        "chess_fur",
        "chess_puck",
        "chess_tp",
        "chess_marci",
        "chess_am",
        "chess_pa",
        "chess_ta",
        "chess_morph",
        "chess_kael"
      ]
    },
    {
      "id": "is_goblin",
      "name": "地精",
      "kind": "race",
      "pieceIds": [
        "chess_clock",
        "chess_tk",
        "chess_bh",
        "chess_shredder",
        "chess_ga",
        "chess_snap",
        "chess_tech"
      ]
    },
    {
      "id": "is_god",
      "name": "神",
      "kind": "race",
      "pieceIds": [
        "chess_mars",
        "chess_oracle",
        "chess_rubick",
        "chess_et",
        "chess_zeus",
        "chess_ts"
      ]
    },
    {
      "id": "is_human",
      "name": "人类",
      "kind": "race",
      "pieceIds": [
        "chess_cm",
        "chess_lina",
        "chess_lyc",
        "chess_lc",
        "chess_dk",
        "chess_light",
        "chess_kunkka",
        "chess_ok"
      ]
    },
    {
      "id": "is_naga",
      "name": "娜迦",
      "kind": "race",
      "pieceIds": [
        "chess_slark",
        "chess_largo",
        "chess_slardar",
        "chess_naga",
        "chess_medusa",
        "chess_th"
      ]
    },
    {
      "id": "is_ogre",
      "name": "食人魔",
      "kind": "race",
      "pieceIds": [
        "chess_om",
        "chess_ga"
      ]
    },
    {
      "id": "is_orc",
      "name": "兽人",
      "kind": "race",
      "pieceIds": [
        "chess_axe",
        "chess_bs",
        "chess_bm",
        "chess_jugg",
        "chess_chen",
        "chess_wl",
        "chess_disruptor"
      ]
    },
    {
      "id": "is_pandaman",
      "name": "熊猫人",
      "kind": "race",
      "pieceIds": [
        "chess_brew"
      ]
    },
    {
      "id": "is_troll",
      "name": "巨魔",
      "kind": "race",
      "pieceIds": [
        "chess_dazzle",
        "chess_ss",
        "chess_wd",
        "chess_bat",
        "chess_huskar",
        "chess_troll"
      ]
    },
    {
      "id": "is_undead",
      "name": "亡灵",
      "kind": "race",
      "pieceIds": []
    },
    {
      "id": "is_tauren",
      "name": "牛头人",
      "kind": "race",
      "pieceIds": [
        "chess_sb",
        "chess_es",
        "chess_et"
      ]
    },
    {
      "id": "is_kobold",
      "name": "狗头人",
      "kind": "race",
      "pieceIds": [
        "chess_meepo",
        "chess_aw"
      ]
    },
    {
      "id": "is_nraqi",
      "name": "无面者",
      "kind": "race",
      "pieceIds": [
        "chess_bane",
        "chess_fv"
      ]
    },
    {
      "id": "is_satyr",
      "name": "萨特",
      "kind": "race",
      "pieceIds": [
        "chess_bane",
        "chess_riki"
      ]
    },
    {
      "id": "is_draenei",
      "name": "德莱尼",
      "kind": "race",
      "pieceIds": [
        "chess_bh",
        "chess_sd",
        "chess_ds",
        "chess_db"
      ]
    },
    {
      "id": "is_centaur",
      "name": "半人马",
      "kind": "race",
      "pieceIds": [
        "chess_eh",
        "chess_ct",
        "chess_mag",
        "chess_ts"
      ]
    },
    {
      "id": "is_harpy",
      "name": "鹰身人",
      "kind": "race",
      "pieceIds": [
        "chess_sm",
        "chess_kez"
      ]
    },
    {
      "id": "is_assassin",
      "name": "刺客",
      "kind": "class",
      "pieceIds": [
        "chess_sb",
        "chess_fv",
        "chess_slark",
        "chess_viper",
        "chess_sk",
        "chess_riki",
        "chess_kez",
        "chess_pa",
        "chess_pangolier",
        "chess_mag",
        "chess_ta",
        "chess_morph",
        "chess_qop"
      ]
    },
    {
      "id": "is_demonhunter",
      "name": "恶魔猎手",
      "kind": "class",
      "pieceIds": [
        "chess_tb",
        "chess_am"
      ]
    },
    {
      "id": "is_druid",
      "name": "德鲁伊",
      "kind": "class",
      "pieceIds": [
        "chess_eh",
        "chess_fur",
        "chess_tp",
        "chess_et",
        "chess_ld",
        "chess_ts"
      ]
    },
    {
      "id": "is_hunter",
      "name": "猎人",
      "kind": "class",
      "pieceIds": [
        "chess_pom",
        "chess_hw",
        "chess_bh",
        "chess_wr",
        "chess_bm",
        "chess_sniper",
        "chess_lyc",
        "chess_medusa",
        "chess_br",
        "chess_th"
      ]
    },
    {
      "id": "is_knight",
      "name": "骑士",
      "kind": "class",
      "pieceIds": [
        "chess_luna",
        "chess_ck",
        "chess_bat",
        "chess_lc",
        "chess_db",
        "chess_dk",
        "chess_snap",
        "chess_ok"
      ]
    },
    {
      "id": "is_mage",
      "name": "法师",
      "kind": "class",
      "pieceIds": [
        "chess_cm",
        "chess_aa",
        "chess_sm",
        "chess_lina",
        "chess_puck",
        "chess_om",
        "chess_phx",
        "chess_light",
        "chess_thd",
        "chess_zeus",
        "chess_kael"
      ]
    },
    {
      "id": "is_mech",
      "name": "工匠",
      "kind": "class",
      "pieceIds": [
        "chess_clock",
        "chess_tk",
        "chess_shredder",
        "chess_meepo",
        "chess_gyro",
        "chess_tech"
      ]
    },
    {
      "id": "is_monk",
      "name": "武僧",
      "kind": "class",
      "pieceIds": [
        "chess_brew",
        "chess_largo",
        "chess_marci",
        "chess_mk"
      ]
    },
    {
      "id": "is_priest",
      "name": "牧师",
      "kind": "class",
      "pieceIds": [
        "chess_dazzle",
        "chess_sd",
        "chess_oracle",
        "chess_chen"
      ]
    },
    {
      "id": "is_shaman",
      "name": "萨满祭司",
      "kind": "class",
      "pieceIds": [
        "chess_ss",
        "chess_bs",
        "chess_razor",
        "chess_es",
        "chess_aw",
        "chess_disruptor"
      ]
    },
    {
      "id": "is_warlock",
      "name": "术士",
      "kind": "class",
      "pieceIds": [
        "chess_bane",
        "chess_wd",
        "chess_ds",
        "chess_enigma",
        "chess_veno",
        "chess_sf",
        "chess_ga",
        "chess_wl",
        "chess_au"
      ]
    },
    {
      "id": "is_warrior",
      "name": "战士",
      "kind": "class",
      "pieceIds": [
        "chess_tusk",
        "chess_axe",
        "chess_mars",
        "chess_jugg",
        "chess_tiny",
        "chess_ct",
        "chess_slardar",
        "chess_huskar",
        "chess_doom",
        "chess_kunkka",
        "chess_troll",
        "chess_pb",
        "chess_sven"
      ]
    },
    {
      "id": "is_wizard",
      "name": "巫师",
      "kind": "class",
      "pieceIds": [
        "chess_dw",
        "chess_gs",
        "chess_naga",
        "chess_rubick",
        "chess_lion"
      ]
    }
  ],
  "io": {
    "id": "chess_io",
    "name": "精灵守卫♥",
    "cost": 5,
    "icon": "/chess-icons/chess_io.png"
  }
};
